# Generated by Django 6.0.1 on 2026-01-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_pedido_itempedido_delete_compralog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Producto Vendido', 'verbose_name_plural': 'Productos Vendidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Venta Realizada', 'verbose_name_plural': 'Ventas Realizadas'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Total'),
        ),
    ]
