# Generated by Django 6.0.1 on 2026-01-18 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_pedido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_log', models.TextField(verbose_name='Detalle de la Actividad')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Registrado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Log')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Compra',
                'verbose_name_plural': 'Logs de Compras',
                'db_table': 'compras_logs',
            },
        ),
    ]
