# Generated by Django 6.0.1 on 2026-01-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_compralog_fecha_compralog_referencia_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compralog',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='compralog',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pedido', verbose_name='Pedido Relacionado'),
        ),
        migrations.AlterField(
            model_name='compralog',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia MP'),
        ),
    ]
