# Generated by Django 6.0.1 on 2026-01-20 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_compralog_fecha_alter_compralog_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Post')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('contenido', models.TextField(verbose_name='Contenido del Post')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor del Post')),
            ],
            options={
                'verbose_name': 'Título del Blog',
                'verbose_name_plural': 'Títulos del Blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
