# Generated by Django 6.0.1 on 2026-01-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_post_slug_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Blog ', 'verbose_name_plural': 'Títulos del Blog'},
        ),
    ]
