# Generated by Django 6.0.1 on 2026-01-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_consulta_alter_post_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
